# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kashyaprajan
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ai-file-reader
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

plugins:
  - serverless-plugin-monorepo

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
